# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='img_url',
            field=models.CharField(default='s3.amazonaws.com/django-proj-bucket/media/photos/treasuregram-arrowhead.png', max_length=255),
            preserve_default=False,
        ),
    ]
