# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20160514_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='image',
        ),
    ]
