# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_treasure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to=main_app.models.get_image_path),
        ),
    ]
