# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20160525_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('treasure', models.ManyToManyField(to='main_app.Treasure')),
            ],
        ),
    ]
