# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-14 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='material',
            new_name='description',
        ),
    ]
