# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20160614_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='description',
        ),
    ]
