# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_treasure_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='treasure',
        ),
        migrations.AddField(
            model_name='treasure',
            name='hashtags',
            field=models.CharField(default='#treasure', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
