# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_treasure_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='treasure',
        ),
        migrations.AddField(
            model_name='treasure',
            name='material',
            field=models.CharField(default='Gold', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
