# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20160706_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
