# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20160707_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 7, 12, 18, 6, 7, 276148, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
