# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_treasure_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='date',
        ),
    ]
